ice:
  image: ice
  command: | 
    -Djava.net.preferIPv4Stack=true
    -Djava.net.preferIPv4Addresses
    -Dice.s3AccessKeyId=<s3AccessKeyId>
    -Dice.s3SecretKey=<s3SecretKeyId>
    run-app
  volumes:
    - ./ice/assets/ice.properties:/opt/ice/src/java/ice.properties
nginx:
  image: nginx
  ports:
    - "80:80"
  links:
    - ice:ice
